config/routes.rb
LocalSupport::Application.routes.draw do
  devise_for :users

  match 'organizations/search' => 'organizations#search'
  match 'pages/disclaimer' => 'pages#disclaimer'
  match 'pages/aboutus' => 'pages#aboutus'
  match 'pages/contact' => 'pages#contact'
  resources :organizations

  root :to => 'organizations#index'

end

app/models/organization.rb
require 'csv'

class Organization < ActiveRecord::Base
  acts_as_gmappable :check_process => false
  has_many :users
  has_and_belongs_to_many :categories
  # Setup accessible (or protected) attributes for your model
  # prevents mass assignment on other fields not in this list
  attr_accessible :name, :description, :address, :postcode, :email, :website, :telephone, :donation_info
  accepts_nested_attributes_for :users

  #This method is overridden to save organization if address was failed to geocode
  def run_validations!
    run_callbacks :validate
    remove_errors_with_address
    errors.empty?
  end
  #TODO: Give this TLC and refactor the flow or refactor out responsibilities
  def update_attributes_with_admin(params)
    email = params[:admin_email_to_add]
    result = false
    if !email.blank?
       result = ActiveRecord::Base.transaction do
         usr = User.find_by_email(email)
         if usr == nil
           self.errors.add(:administrator_email, "The user email you entered,'#{email}', does not exist in the system")
           raise ActiveRecord::Rollback
         else
           self.users << usr
           self.update_attributes(params)
         end
       end
    else
      result = self.update_attributes(params)
    end
    return result
  end

  def self.search_by_keyword(keyword)
    self.where("UPPER(description) LIKE ? OR UPPER(name) LIKE ?","%#{keyword.try(:upcase)}%","%#{keyword.try(:upcase)}%")
  end

  def self.filter_by_category(category_id)
    return scoped unless category_id.present?
    # could use this but doesn't play well with search by keyqord since table names are remapped
    #Organization.includes(:categories).where("categories_organizations.category_id" =>  category_id)
    category = Category.find_by_id(category_id)
    orgs = category.organizations.each {|org| org.id} if category
    where(:id => orgs)
  end

  def gmaps4rails_address
    "#{self.address}, #{self.postcode}"
  end

  def gmaps4rails_infowindow
    "#{self.name}"
  end

  def self.humanize_description(unfriendly_description) 
    unfriendly_description && unfriendly_description.humanize
  end

  def self.parse_address(address_with_trailing_postcode)  
    address = address_with_trailing_postcode.to_s
    postcode = ''
    match = address_with_trailing_postcode.to_s.match(/(.*)(,\s*(\w\w\d\s* \d\w\w))/)
    if match
      if match.length == 4 
        address = match[1]
        postcode = match[3].to_s
      end
    end
    {:address => address, :postcode => postcode}
  end

  #Edit this if CSV 'schema' changes
  #value is the name of a column in csv file
  @@column_mappings = {
      name: 'Title',
      address: 'Contact Address',
      description: 'Activities',
      website: 'website',
      telephone: 'Contact Telephone',
      date_removed: 'date removed',
      cc_id: 'Charity Classification'
  }
  def self.column_mappings
    @@column_mappings
  end
  def self.import_categories_from_array(row)
    check_columns_in(row)
    org = Organization.find_by_name(row[@@column_mappings[:name]].to_s.humanized_all_first_capitals)
    if org
      category_ids = row[@@column_mappings[:cc_id]]
      if category_ids
        category_ids.split(',').each do |id|
          cat = Category.find_by_charity_commission_id(id.to_i)
          org.categories << cat
        end
      end
    end
    org
  end

  def self.import_category_mappings(filename, limit)
    csv_text = File.open(filename, 'r:ISO-8859-1')
    count = 0
    CSV.parse(csv_text, :headers => true).each do |row|
      if count >= limit
        break
      end
      count += 1
      begin
        self.import_categories_from_array(row)
      rescue CSV::MalformedCSVError => e
        logger.error(e.message)
      end
    end
  end
  def self.create_from_array(row, validate)
    check_columns_in(row)
    return nil if row[@@column_mappings[:date_removed]]
    address = self.parse_address(row[@@column_mappings[:address]])

    org = Organization.new
    org.name = row[@@column_mappings[:name]].to_s.humanized_all_first_capitals
    #POSSIBLE APPPROACH BELOW ... OR COULD PUT ALL NEW STUFF IN SEPARATE METHOD CALLED UPDATE_CATEGORIES
    # grab all classifications
    if Organization.find_by_name(org.name)
      # check for classifications and add as necessary
      # add them to existing organization
      return nil
    end
    # add them to new organization

    org.description = self.humanize_description(row[@@column_mappings[:description]])
    org.address = address[:address].humanized_all_first_capitals
    org.postcode = address[:postcode]
    org.website = row[@@column_mappings[:website]]
    org.telephone = row[@@column_mappings[:telephone]]

    # this commented throttling code might work well for db:seed, but
    # relies of hard validation failures, which we must avoid
    # in the normal operation of the app
    #begin
      org.save! validate: validate
    #rescue ActiveRecord::RecordInvalid => e
      #if e.message =~ /Gmaps4rails address Address invalid/
        #begin
          #Gmaps4rails.geocode(org.gmaps4rails_address)
        #rescue Gmaps4rails::GeocodeStatus => e
          #if e.message =~ /OVER_QUERY_LIMIT/
            ## throttle the rate of saves
            #sleep(2000)
            #org.save! validate: validate
          #end
        #end
      #end
    #end

    org
  end

  def self.import_addresses(filename, limit, validation = true)
    csv_text = File.open(filename, 'r:ISO-8859-1')
    count = 0
    CSV.parse(csv_text, :headers => true).each do |row|
      if count >= limit
        break
      end
      count += 1
      begin
        self.create_from_array(row, validation)
      rescue CSV::MalformedCSVError => e
        logger.error(e.message)
      end
    end
  end

  def self.check_columns_in(row)
    @@column_mappings.each_value do |column_name|
      unless row.header?(column_name)
        raise CSV::MalformedCSVError, "No expected column with name #{column_name} in CSV file"
      end
    end
  end

  private

  def remove_errors_with_address
    errors_hash = errors.to_hash
    errors.clear
    errors_hash.each do |key, value|
      logger.warn "#{key} --> #{value}"
      if key.to_s != 'gmaps4rails_address'
        errors.add(key, value)
      else
        # nullify coordinates
        self.latitude = nil
        self.longitude = nil
      end
    end
  end
end

class String
  def humanized_all_first_capitals
    self.humanize.split(' ').map{|w| w.capitalize}.join(' ')
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  # GET /organizations/search
  # GET /organizations/search.json
  before_filter :authenticate_user!, :except => [:search, :index, :show]
  def search
    # should this be a model method with a model spec around it ...?

    @query_term = params[:q]
    @category_id = params["category"]["id"] if !params["category"].nil? && !params["category"]["id"].blank?
    @category = Category.find_by_id(@category_id) unless @category_id.blank?

    @organizations = Organization.search_by_keyword(@query_term).filter_by_category(@category_id)

    flash.now[:alert] = "Sorry, it seems we don't quite have what you are looking for." if @organizations.empty?
    @json = gmap4rails_with_popup_partial(@organizations,'popup')
    @category_options = Category.where('charity_commission_id < 199').order('name ASC').collect {|c| [ c.name, c.id ] }
    respond_to do |format|
      format.html { render :template =>'organizations/index'}
      format.json { render json:  @organizations }
      format.xml  { render :xml => @organizations }
    end
  end

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.order("updated_at DESC")
    @json = gmap4rails_with_popup_partial(@organizations,'popup')
    @category_options = Category.where('charity_commission_id < 199').order('name ASC').collect {|c| [ c.name, c.id ] }
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organizations }
      format.xml  { render :xml => @organizations }
    end
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.find(params[:id])
    @editable = current_user.can_edit?(@organization) if current_user
    @json = gmap4rails_with_popup_partial(@organization,'popup')
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    @organization = Organization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    #TODO Eliminate code duplication for permissoins across methods
    @organization = Organization.find(params[:id])
    unless current_user.try(:can_edit?,@organization)
      flash[:notice] = "You don't have permission"
      redirect_to organization_path(params[:id]) and return false
    end
  end

  # POST /organizations
  # POST /organizations.json
  def create
    # model filters for logged in users, but we check here if that user is an admin
    # TODO refactor that to model responsibility?
     unless current_user.try(:admin?)
       flash[:notice] = "You don't have permission"
       redirect_to organizations_path and return false
     end
    @organization = Organization.new(params[:organization])

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])
    params[:organization][:admin_email_to_add] = params[:organization_admin_email_to_add] if params[:organization]
    unless current_user.try(:can_edit?,@organization)
      flash[:notice] = "You don't have permission"
      redirect_to organization_path(params[:id]) and return false
    end
    respond_to do |format|
      if @organization.update_attributes_with_admin(params[:organization])
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    unless current_user.try(:admin?)
      flash[:notice] = "You don't have permission"
      redirect_to organization_path(params[:id]) and return false
    end
    @organization = Organization.find(params[:id])
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :ok }
    end
  end

  private
  def gmap4rails_with_popup_partial(item, partial)
    item.to_gmaps4rails  do |org, marker|
      marker.infowindow render_to_string(:partial => partial, :locals => { :@org => org})
    end
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
  def donation_info_msg 
     @organization.donation_info.blank? ? "We don't yet have any donation link for them." : link_to("Donate to #{@organization.name} now!", @organization.donation_info, {:target => '_blank'})
  end
  def charity_admin_display_msg
    render :partial => 'organizations/charity_admin_display'
  end
end

app/views/organizations/_charity_admin_display.erb
<% if @organization.users.empty? %>
    <div>This organisation has no admins yet</div>
<% else %>
  <div>
  Organisation administrator emails:
  <ol>
  <% @organization.users.each do |admin| %>
  <li><%= admin.email %></li>
  <% end %>
  </ol>
  </div>
<% end %>

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "org_form" %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address, :class => "org_form" %>
  </div>
  <div class="field">
    <%= f.label :postcode %>
    <%= f.text_field :postcode, :class => "org_form" %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, :class => "org_form" %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :class => "org_form", :cols => "10", :rows => "10" %>
  </div>
  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website, :class => "org_form" %>
  </div>
  <div class="field">
    <%= f.label :telephone %>
    <%= f.text_field :telephone, :class => "org_form" %>
  </div>
  <div>
     <%= f.label :donation_info %>
     <%= f.text_field :donation_info, :class => "org_form" %>
  </div>
  <%= charity_admin_display_msg %>
  <div class="field">
    <%= label_tag :organization_admin_email_to_add, "Add an additional organisation administrator email" %>
    <%= text_field_tag 'organization_admin_email_to_add', value = nil, {:size => 100, class: 'org_form'} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/_popup.html.erb
<%= link_to @org.name, organization_path(@org) %><br/>
<%= smart_truncate(@org.description,32) %>

app/views/organizations/edit.html.erb
<h1>Editing organisation</h1>

<%= render 'form' %>

app/views/organizations/index.html.erb
<br/>
<br/>
<%= form_tag("/organizations/search", :method => "get") do %>
    <%= label_tag(:q, "Select Category:") %>
    <%= select("category", "id", @category_options, { :include_blank => 'All' }, {:style => 'margin-bottom: 5px;'}) %>
    <%= submit_tag "Submit", {:class => 'btn btn-info',:style => 'margin-bottom: 5px;'} %>
    <%= text_field_tag(:q, @query_term || '', {:style => 'margin-bottom: 5px; width: 240px;', :placeholder => "optional search name/description" }) %>
<% end %>
<div id="orgs_scroll" style="height:300px;width:100%;border:1px solid #ccc;overflow:scroll;">
    <div class="table table-bordered">
      <table>
        <div id="organizations">
            <% @organizations.each do |organization| %>
                <tr>
                  <td><u><%= link_to organization.name, organization %></u><br/>
                    <%= smart_truncate(organization.description) %></td>
                </tr>
            <% end %>
        </div>
      </table>
    </div>
</div>
<br/>
<div style="width:50%;float:left">
  <%= link_to_if(current_user.try(:admin?), 'New Organization', new_organization_path){} %>
</div>

<% content_for :map do %>
    <br/><br/>
    <%= gmaps("map_options" => {"auto_adjust" => false, "auto_zoom" => true, "center_latitude" => 51.5978,
                                "center_longitude" => -0.3370, "zoom" => 12}, "markers" => {"data" => @json}) %>
<% end %>

app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p></p>

<p>
  <b>Name:</b>
  <%= @organization.name %>
</p>

<p>
  <b>Postcode:</b>
  <%= @organization.postcode %>
</p>

<p>
  <b>Email:</b>
  <%= @organization.email %>
</p>

<p>
  <b>Description:</b>
  <%= @organization.description %>
</p>

<p>
  <b>Website:</b>
  <%= link_to_if(!@organization.website.blank?, @organization.website, @organization.website, {:target => '_blank'}){"We don't yet have a website link for them."}  %>
</p>

<p><b>Donation Info:</b>
<%= donation_info_msg %>
</p>

<%= link_to_if(@editable, "Edit", edit_organization_path(@organization.id), {:class => 'btn btn-large'}){} %>

<% content_for :map do %>
    <%= gmaps("map_options" => {"auto_adjust" => true, "auto_zoom" => false, "center_latitude" => 51.5978,
                                "center_longitude" => -0.3370, "zoom" => 13}, "markers" => {"data" => @json}) %>
<% end %>