config/routes.rb
LocalSupport::Application.routes.draw do
  devise_for :users

  match 'organizations/search' => 'organizations#search'
  match 'pages/disclaimer' => 'pages#disclaimer'
  match 'pages/aboutus' => 'pages#aboutus'
  match 'pages/contact' => 'pages#contact'
  resources :organizations

  root :to => 'organizations#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Harrow Community Network
    provided by <a href="http://www.voluntaryactionharrow.org.uk/">Voluntary Action Harrow</a>
  </small>
</footer>

app/views/layouts/_footer2.html.erb
<footer class="footer">
   <p class="text-center"><small>
     Powered by <%= link_to image_tag("rails.png", :size =>"20x12", alt:"RubyonRails"), 'http://rubyonrails.org/' %>&nbsp &nbsp &nbsp &nbsp &nbsp
   </small> </p>
</footer>

app/views/layouts/_footer3.html.erb
<footer class="footer">
  <p class="text-right"><small>
    <a href=<%= pages_contact_path %>>Contact  </a> /
    <a href=<%= pages_aboutus_path %>> About Us</a>
  </small></p>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
       <div class="row">
        <div class="span6">
          <%= link_to(image_tag("HCN2.png", :style => "width:200px;height:72px;" ), root_path) %>
          <%= image_tag("beta.jpg", :style => "width:75px;") %>
        </div>
        <% if (user_signed_in?)%>
       <div class="span6">
         Signed in as <%= current_user.email %>.  <%=link_to "Not you?", destroy_user_session_path, :method => :delete%>
       </div>
       <% end %>
      <div class="span6">
      <nav>
        <ul class="nav pull-right" style="padding-top:17px;">
          <li><%= link_to "Home", root_path %></li>
          <li><% if (user_signed_in?)%>
          <%=link_to "Sign Out", destroy_user_session_path, :method => :delete%>
          <% end %></li>
          <li><% if !(user_signed_in?)%>
          <%= link_to "New Org?", new_user_registration_path %>
          <% end %></li>
          <li><% if !(user_signed_in?)%>
          <%= link_to "Org Login", user_session_path %>
          <% end %></li>
          <li><%= link_to "Disclaimer", pages_disclaimer_path %></li>
        </ul>
      </nav>
      </div>
  </div>
  </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
     <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Harrow Community Network</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

<body>
<% flash.each do |name, msg| %>
<%= content_tag :div, msg, :class => "flash #{name}" %>
<% end %>

<%= render 'layouts/header' %>
<div class="container">
<div class="row">
  <div class="span6">
    <%= yield :map %>
  </div>
  <div class="span6">
    <%= yield %>
  </div>
</div>
<br>
<br>
<div class="row">
  <div class="span4">
    <%= render 'layouts/footer' %>
  </div>
  <div class="span4">
    <%= render 'layouts/footer2' %>
  </div>
  <div class="span4">
    <%= render 'layouts/footer3' %>
  </div>
</div>
</div>
<!--this is where the gmaps scripts are added-->
<%= yield :scripts %>
</body>
</html>